<a href="https://colab.research.google.com/github/amathe1/GenAI-AgenticAI-Hub/blob/main/PyTorch_17_18_Jan_2026_Updated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch


*   PyTorch is a deep learning framwork developed by Meta
*   It is used to build and train neural networks
*   Very pythonic and easy to debug
*   Popular in research & production
*   Uses dynamic computational graphs

In [ ]:
# How to import PyTorch module ?

"""
torch       → core deep learning engine
torchvision → vision tools
torchaudio  → audio tools
"""

!pip install torch torchvision torchaudio

In [ ]:
# How to confirm imported PyTorch version ?

import torch

print(torch.__version__)

2.9.0+cu126


In [ ]:
# How to check if CUDA is avaialable or not ?

"""
CUDA is NVIDIA's GPU which we need for complex calculations

"""

if torch.cuda.is_available():
  print("GPU is available")
else:
  print("GPU is not available")

GPU is available


# Creating a Tensor !

- A tensor is a multi-dimensional data structure used to store and process data in deep learning.

In [ ]:
import torch

# torch.empty() creates a tensor without initializing values
# Memory is allocated, but values are random
# Values are not zero
# They depend on whatever was already in memory
a = torch.empty(2,3) # 2 * 3 matrix

# printing the tensor
print(a)
"""
tensor([[4.2104e-32, 4.5144e-41, 1.6045e-12],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
"""

# Type
print(type(a)) # <class 'torch.Tensor'>

tensor([[4.2104e-32, 4.5144e-41, 1.6045e-12],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
<class 'torch.Tensor'>


In [ ]:
# Create a tensor with values as zero

b = torch.zeros(3,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Create a tensor with values as ones

c = torch.ones(3,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Create a tensor with random as ones

d = torch.rand(3,3)
d

# Note that when we use rand(), values will change in each iteration/execution

tensor([[0.9804, 0.6721, 0.7868],
        [0.7468, 0.6994, 0.5058],
        [0.3881, 0.0183, 0.4398]])

In [ ]:
# Create a tensor with random values; BUT should not change in each iteration

torch.manual_seed(100)
e = torch.rand(3,3)
e

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [ ]:
# Create a tensor with some linear values

f = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(f)
f.shape

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


torch.Size([3, 3])

In [ ]:
# Create a tensor starting from value '0' till '100' with step as 3
# Means it will start from zero and print every 3rd number till 100

g = torch.arange(0,100,3)
g

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
# It creates evenly spaced numbers between start and end.

h = torch.linspace(1,10,30)
print(h)
print(h.shape)

tensor([ 1.0000,  1.3103,  1.6207,  1.9310,  2.2414,  2.5517,  2.8621,  3.1724,
         3.4828,  3.7931,  4.1034,  4.4138,  4.7241,  5.0345,  5.3448,  5.6552,
         5.9655,  6.2759,  6.5862,  6.8966,  7.2069,  7.5172,  7.8276,  8.1379,
         8.4483,  8.7586,  9.0690,  9.3793,  9.6897, 10.0000])
torch.Size([30])


In [ ]:
# Create an indentity matrix tensor

i = torch.eye(3)
i

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
# It will create a 3 * 4 matrix with values as 5
j = torch.full((3,4),5)
j

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

In [ ]:
# Checking the type

j.dtype

torch.int64

In [ ]:
# Type casting Tensor


k = torch.tensor([1.0, 2.0, 3.0], dtype=float)
print(k)


l = k.to(torch.int)
print(l)

print(l.shape)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3], dtype=torch.int32)
torch.Size([3])


In [ ]:
# Adding a number to each element in tensor

m = l+2
print(m)

tensor([3, 4, 5], dtype=torch.int32)


In [ ]:
import torch

# Enabling auto grad using requires_grad=True
x = torch.tensor(2.0, requires_grad=True)



In [ ]:
y = 2*x + 3

y

tensor(7., grad_fn=<AddBackward0>)

In [ ]:
# It started backward propagation and goes until leaf node, nothing but starting point of computational graph
y.backward()

In [ ]:
# print x.grad to see the gradient
print(x.grad)

# Output : tensor(2.)

tensor(2.)


In [ ]:
import torch

x1 = torch.tensor(3.0, requires_grad=True)
y = (2*x1 + 3)**2
print(y) # tensor(81., grad_fn=<PowBackward0>)
y.backward() # backward propagation initiated
print(x1.grad) # Printing gradinet of x :  tensor(36.)
x1.grad.zero_ # if we don't set x1.grad.zero_ then result will be accumulated each time you run this program

"""
Example:
Find d/dx(2x+3)²

We apply the formula:

d/dx[g(x)ⁿ] = n[g(x)]ⁿ⁻¹ · g'(x)

Step 1: Identify inner function
g(x) = 2x + 3

Step 2: Identify power
n = 2

Step 3: Apply formula

d/dx(2x+3)²
= 2(2x+3)²⁻¹ · d/dx(2x+3)

= 2(2x+3)¹ · 2

Step 4: Simplify

= 4(2x+3)

Final Answer:
d/dx(2x+3)² = 4(2x+3)

"""

tensor(81., grad_fn=<PowBackward0>)
tensor(36.)


"\nExample:\nFind d/dx(2x+3)²\n\nWe apply the formula:\n\nd/dx[g(x)ⁿ] = n[g(x)]ⁿ⁻¹ · g'(x)\n\nStep 1: Identify inner function\ng(x) = 2x + 3\n\nStep 2: Identify power\nn = 2\n\nStep 3: Apply formula\n\nd/dx(2x+3)²\n= 2(2x+3)²⁻¹ · d/dx(2x+3)\n\n= 2(2x+3)¹ · 2\n\nStep 4: Simplify\n\n= 4(2x+3)\n\nFinal Answer:\nd/dx(2x+3)² = 4(2x+3)\n\n"